server:
  port: 8080
spring:
  application:
    name: gamification
  liquibase:
    url: jdbc:postgres://postgres:5432/game
    user: ${POSTGRES_USERNAME:game}
    password: ${POSTGRES_PASSWORD}
  r2dbc:
    url: r2dbc:postgres://postgres:5432/game
    username: ${POSTGRES_USERNAME:game}
    password: ${POSTGRES_PASSWORD}
    pool:
      max-size: 10
      max-idle-time: 5
      validation-query: SELECT 1
  netty:
    leak-detection: paranoid
  webflux:
    base-path: /game
management:
  endpoint:
    restart:
      enabled: false
    refresh:
      enabled: false
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /game/v3/api-docs
  api-docs:
    enabled: true
    path: /game/v3/api-docs
logging:
  level:
    io.lonmstalker: DEBUG
    root: INFO
