server:
  port: 8080

spring:
  application:
    name: gamification
  liquibase:
    url: jdbc:postgresql://localhost:5432/game
    user: ${POSTGRES_USERNAME:game}
    password: ${POSTGRES_PASSWORD:game}
    changeLog: classpath:db/changelog/master.yml
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/game
    username: ${POSTGRES_USERNAME:game}
    password: ${POSTGRES_PASSWORD:game}
    pool:
      enabled: true
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1
  netty:
    leak-detection: paranoid
  webflux:
    base-path: /game

app:
  blockchainApiUrl: ${BLOCKCHAIN_URL:https://hackathon.lsp.team/hk}

management:
  endpoint:
    restart:
      enabled: false
    refresh:
      enabled: false

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /game/v3/api-docs/swagger-config
    url: /game/v3/api-docs
    disable-swagger-default-url: true
  api-docs:
    enabled: true
    path: /v3/api-docs

logging:
  level:
    io.lonmstalker: DEBUG
    root: ERROR
