version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: "game"
      POSTGRES_USER: ${POSTGRES_USER:-game}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-game}
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: on-failure
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: ${AUTH_USER:-auth}
      DB_PASSWORD: ${AUTH_PASSWORD:-auth}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    volumes:
      - keycloak:/data/keycloak
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"

  game:
     build:
       context: ..
       dockerfile: gamification-impl/Dockerfile
     container_name: game
     restart: on-failure
     environment:
       POSTGRES_USERNAME: game
       POSTGRES_PASSWORD: game
       KEYCLOAK_REALM_CERT_URL: http://localhost:8082/auth
       BLOCKCHAIN_URL: https://hackathon.lsp.team/hk
     ports:
       - "8082:8080"
     depends_on:
       - postgres

  auth:
    build:
      context: ..
      dockerfile: gamification-auth/Dockerfile
    container_name: auth
    restart: on-failure
    environment:
      POSTGRES_USERNAME: auth
      POSTGRES_PASSWORD: auth
      AUTH_URL: http://localhost:8082/auth
    ports:
      - "8084:8080"
    depends_on:
      - postgres
      - keycloak

volumes:
  keycloak:
